### ISSUE TITLE
[Question]搜索的时候会出错怎么办

### ISSUE THREAD

**Issue by cntommy** [MLNLP-World/AI-Paper-Collector#67]
**Question**
本地和colab上执行都会出错，请问下这怎么解决呢

**Screenshots**

Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 43, in main
    results = exec_search(indexes, candidates, query, mode, threshold, confs, limit)
  File "/content/AI-Paper-Collector/searcher.py", line 179, in exec_search
    results = exact_search(indexes, query, confs)
  File "/content/AI-Paper-Collector/searcher.py", line 86, in exact_search
    results = [item for item in indexes if query in item[1].lower()]
  File "/content/AI-Paper-Collector/searcher.py", line 86, in <listcomp>
    results = [item for item in indexes if query in item[1].lower()]
AttributeError: 'dict' object has no attribute 'lower'

**Comment by Doragd** [comment]
本地版本似乎存在问题，我会在一段时间后fix，在这之前，推荐使用web版本
