### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhou6140919** [MLNLP-World/AI-Paper-Collector#78]
This error happens when you input list of conferences.

```bash
[+] Enter your list of conferences (default: All Confs): ACL,EMNLP,NAACL,COLING,ICLR,AAAI
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 43, in main
    results = exec_search(indexes, candidates, query, mode, threshold, confs, limit)
  File "/cephfs/zhoutong/work/AI-Paper-Collector/searcher.py", line 179, in exec_search
    results = exact_search(indexes, query, confs)
  File "/cephfs/zhoutong/work/AI-Paper-Collector/searcher.py", line 86, in exact_search
    results = [item for item in indexes if query in item[1].lower()]
  File "/cephfs/zhoutong/work/AI-Paper-Collector/searcher.py", line 86, in <listcomp>
    results = [item for item in indexes if query in item[1].lower()]
AttributeError: 'dict' object has no attribute 'lower'
```

**Comment by zhou6140919** [comment]
sorry, i didn't notice that there was a similar error.
