### ISSUE TITLE
[BUG]AttributeError: 'dict' object has no attribute 'lower'

### ISSUE THREAD

**Issue by zihao-ai** [MLNLP-World/AI-Paper-Collector#80]
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 43, in main
    results = exec_search(indexes, candidates, query, mode, threshold, confs, limit)
  File "/home/zhuzihao/AI-Paper-Collector/searcher.py", line 179, in exec_search
    results = exact_search(indexes, query, confs)
  File "/home/zhuzihao/AI-Paper-Collector/searcher.py", line 86, in exact_search
    results = [item for item in indexes if query in item[1].lower()]
  File "/home/zhuzihao/AI-Paper-Collector/searcher.py", line 86, in <listcomp>
    results = [item for item in indexes if query in item[1].lower()]
AttributeError: 'dict' object has no attribute 'lower'

**Comment by zihao-ai** [comment]
这一版bug太多了，没有之前一版好用，生成的txt也很不直观

**Comment by Doragd** [comment]
ref: https://github.com/MLNLP-World/AI-Paper-Collector/issues/67
